clades:
  - "24A"
  - "24B"
  - "24C"
  - "24E"
  - "24F"
  - "24H"
  - "24I"
  - "25A"
  - "recombinant"
  - "other"

target_date: "2025-02-12"

data: "./Data/Virus counts"
          
