clades:
  - "24A"
  - "24B"
  - "24C"
  - "24E"
  - "24F"
  - "24G"
  - "24H"
  - "24I"
  - "recombinant"
  - "other"

target_date: "2024-12-04"

data: "./Data/Virus counts"
          
